---
title: "Google News Headlines"
author: "William Pattison"
date: "8/15/2019"
output: html_document
---

Load packages

```{r setup, include=FALSE}
library(tidytext)
library(tidyverse)
library(wordcloud)
library(RColorBrewer)
```

Read Data

```{r}
nz_headlines_data <- read.csv("NZHeadlines.csv")
latest_headline_data <- read.csv("LatestHeadlines.csv")
```

Information for NZ Headlines (Whole dataset)

```{r}
headlines <- tibble(Headline = as.character(nz_headlines_data$Headline))

# data frame with words extracted from headlines (without stop words)
word_data <- headlines %>%
  unnest_tokens(word, Headline) %>%
  anti_join(stop_words)

# used to remove all numbers i.e 500k, 500m, 500.0, 500 and strange cases like te22st etc
tidy_data <- word_data[-grep("\\w*[0-9]+\\w*\\s*", word_data$word),] 

#add frequencies
tidy_data <- tidy_data %>%
  count(word, sort = T)

#create word cloud
wordcloud(
  words = tidy_data$word, freq = tidy_data$n, min.freq = 50,
  max.words = 200, random.order = FALSE, rot.per = 0.35,
  colors = brewer.pal(8, "Dark2"))

tidy_data %>%
  filter(n > 50) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_col() +
  xlab(NULL) +
  coord_flip()
```


Information for NZ Latest Headlines (Whole dataset)

```{r}
headlines <- tibble(Headline = as.character(latest_headline_data$Headline))

# data frame with words extracted from headlines (without stop words)
word_data <- headlines %>%
  unnest_tokens(word, Headline) %>%
  anti_join(stop_words)

# used to remove all numbers i.e 500k, 500m, 500.0, 500 and strange cases like te22st etc
tidy_data <- word_data[-grep("\\w*[0-9]+\\w*\\s*", word_data$word),] 

#add frequencies
tidy_data <- tidy_data %>%
  count(word, sort = T)

#create word cloud
wordcloud(
  words = tidy_data$word, freq = tidy_data$n, min.freq = 50,
  max.words = 200, random.order = FALSE, rot.per = 0.35,
  colors = brewer.pal(8, "Dark2"))

tidy_data %>%
  filter(n > 50) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_col() +
  xlab(NULL) +
  coord_flip()
```


Daily information for NZ Latest Headlines

```{r}
today_news <- latest_headline_data %>%
  filter(Date == as.character(Sys.Date()))

headlines <- tibble(Headline = as.character(today_news$Headline))

# data frame with words extracted from headlines (without stop words)
word_data <- headlines %>%
  unnest_tokens(word, Headline) %>%
  anti_join(stop_words)        

# used to remove all numbers i.e 500k, 500m, 500.0, 500 and strange cases like te22st etc
tidy_data <- word_data[-grep("\\w*[0-9]+\\w*\\s*", word_data$word),] 

#add frequencies
tidy_data <- tidy_data %>%
  count(word, sort = T)

#create word cloud
wordcloud(
  words = tidy_data$word, freq = tidy_data$n, min.freq = 5,
  max.words = 200, random.order = FALSE, rot.per = 0.35,
  colors = brewer.pal(8, "Dark2"))

tidy_data %>%
  filter(n > 5) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_col() +
  xlab(NULL) +
  coord_flip()
```



Daily information for NZ Headlines

```{r}
today_news <- nz_headlines_data %>%
  filter(Date == as.character(Sys.Date()))

headlines <- tibble(Headline = as.character(today_news$Headline))

# data frame with words extracted from headlines (without stop words)
word_data <- headlines %>%
  unnest_tokens(word, Headline) %>%
  anti_join(stop_words)        

# used to remove all numbers i.e 500k, 500m, 500.0, 500 and strange cases like te22st etc
tidy_data <- word_data[-grep("\\w*[0-9]+\\w*\\s*", word_data$word),] 

#add frequencies
tidy_data <- tidy_data %>%
  count(word, sort = T)

#create word cloud
wordcloud(
  words = tidy_data$word, freq = tidy_data$n, min.freq = 5,
  max.words = 200, random.order = FALSE, rot.per = 0.35,
  colors = brewer.pal(8, "Dark2"))

tidy_data %>%
  filter(n > 5) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_col() +
  xlab(NULL) +
  coord_flip()
```

Most popular publisher for NZ Headlines and Latest NZ Headlines

```{r}
nz_headlines_data %>% 
  group_by(Publisher) %>% 
  summarize(count = n()) %>%
  filter(count > 50) %>%
  ggplot(aes(Publisher, count)) +
  geom_col() +
  ggtitle("Count vs publisher for NZ Headlines") +
  theme(plot.title = element_text(hjust = 0.5))

latest_headline_data %>% 
  group_by(Publisher) %>% 
  summarize(count = n()) %>%
  filter(count > 50) %>%
  ggplot(aes(Publisher, count)) +
  geom_col() +
  ggtitle("Count vs publisher for Latest NZ Headlines") +
  theme(plot.title = element_text(hjust = 0.5))
```









